### Dataset API call 
GET http://localhost:3000/api/dataset/api_1_canopy?page=3
accept: application/json

### KONG ADMIN ROOT URL
GET http://localhost:8001
accept: application/json

### KONG add service
POST http://localhost:8001/services
accept: application/json
Content-Type: application/json

{
  "name": "stores4",
  "url": "http://localhost:3000/api/dataset/stores4"
}

### KONG check plugin status
GET http://localhost:8001/plugins

### api call test through kong
GET http://localhost:8000/api/v1/dataset/api_1_stores3
accept: application/json
Content-Type: application/json
apikey: testkey

### api call test through kong
GET http://localhost:3000/api/dataset/api_1_stores4
accept: application/json
Content-Type: application/json
apikey: testkey


### simple login JWT
POST http://localhost:3000/oauth/login
accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### simple refresh JWT
POST http://localhost:3000/oauth/token
accept: application/json
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTU5MTY5NDE2NiwiZXhwIjoxNTk0Mjg2MTY2fQ.q9Uk-GRdsCYnRzDTl1hWqHGfXqn90ftx8aGHdKsGeTY"
}